import { PrismaClient } from "@prisma/client";
const p = new PrismaClient();
const junk = [
    'BONCAUTREOTUONGCAOCA', 'BONCAUTRUNGTHONGMINH', 'SENCAYAMTRAN', 'SENCAYPHIMDAN',
    'SENCAYTAMTRUYENTHONG', 'PHUKIENNHATAM', 'COMBOPHONGTAM', 'DENDIEUHOAPHONGTAM',
    'DAILYSEAJONG', 'HUONGDANLAPDATPHONGB', 'HUONGDANLAPDATPHONGT', 'TIPSCHAMSOCNHACUA',
    'PHONGTHUYNHA', 'THONGTINKHUYENMAI', 'TUYENDUNG', 'HETHONGSHOWROOM',
    'CHINHSACHTHANHTOANCU', 'CHINHSACHBAOHANHBAOT', 'CHINHSACHBAOMAT',
    'CHINHSACHGIAOHANGKIE', 'CHINHSACH1DOI1', 'CHINHSACHTRAGOP0LAIS',
    'CHINHSACHDAILYTHIETB', 'KHUYENMAI'
];
p.product.deleteMany({ where: { code: { in: junk } } })
    .then((r: any) => console.log("Deleted", r.count, "junk records"))
    .finally(() => p.$disconnect());
